cluster.name: es  #集群名
node.name: es-04 #节点名

node.data: true  #该节点是否存储数据
node.master: true #不做主节点
# node.attr.rack: hot
node.attr.group: cold
network.host: 127.0.0.1
http.port: 9204 #节点对外端口
transport.tcp.port: 9304 #节点通信端口
discovery.zen.ping.unicast.hosts: ["127.0.0.1:9300","127.0.0.1:9301" ,"127.0.0.1:9302","127.0.0.1:9303","127.0.0.1:9304"]
node.max_local_storage_nodes: 10  #单机最大节点数
path.data: /Applications/XAMPP/xamppfiles/htdocs/test/ELK/es-04/data
path.logs: /Applications/XAMPP/xamppfiles/htdocs/test/ELK/es-04/logs
http.cors.enabled: true
http.cors.allow-origin: "*"

discovery.zen.minimum_master_nodes: 2


xpack.security.enabled: false

# xpack.security.enabled: true
#xpack.security.transport.ssl.enabled: false
xpack.security.user: "elastic:Gaoji_001#"

xpack.ssl.key: /Applications/XAMPP/xamppfiles/htdocs/test/ELK/es-04/config/ca/ca.key 
xpack.ssl.certificate: /Applications/XAMPP/xamppfiles/htdocs/test/ELK/es-04/config/ca/ca.crt 
xpack.ssl.certificate_authorities: [ "/Applications/XAMPP/xamppfiles/htdocs/test/ELK/es-04/config/ca/ca.crt"]


http.cors.allow-headers: Authorization

# xpack.monitoring.enabled: false
# xpack.graph.enabled: false
# xpack.watcher.enabled: false


#xpack.ssl.key: /usr/local/src/elasticsearch-5.5.1/config/ca/ca.key 
#xpack.ssl.certificate: /usr/local/src/elasticsearch-5.5.1/config/ca/ca.crt 
#xpack.ssl.certificate_authorities: [ "/usr/local/src/elasticsearch-5.5.1/config/ca/ca.crt"]

#xpack.ssl.key: /usr/share/elasticsearch/ca/ca.key 
#xpack.ssl.certificate: /usr/share/elasticsearch/ca/ca.crt 
#xpack.ssl.certificate_authorities: [ "/usr/share/elasticsearch/ca/ca.crt"]







# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
#
# Path to log files:
#
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
